In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('wssinfo_data_cleaned.csv')

In [8]:
df.head()

,Country,Year,Population Urban (x1000),Population Urban (% Total),Population Rural (x1000),Population Rural (% Total),Population (x 1000),Water Urban Total Improved (x1000),Water Urban Total Improved (%),Water Urban Piped on Premises (x1000),...,Sanitation National Total Improved (x1000),Sanitation National Total Improved (%),Sanitation National Total Unimproved (x1000),Sanitation National Total Unimproved (%),Sanitation National Shared (x1000),Sanitation National Shared (%),Sanitation National Other Unimproved (x1000),Sanitation National Other Unimproved (%),Sanitation National Open Defecation (x1000),Sanitation National Open Defecation (%)
0,Afghanistan,1990,2130.0,18.2,9601.2,81.8,11731.2,NaN,NaN,65.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1991,2319.2,18.4,10292.8,81.6,12612.0,324.0,14,71.6,...,2640.0,20.9,9972.1,79.1,951.3,7.5,4817.9,38.2,4202.9,33.324284
2,Afghanistan,1992,2572.3,18.6,11239.6,81.4,13811.9,359.4,14,79.4,...,2893.1,20.9,10918.7,79.1,1043.5,7.6,5279.5,38.2,4595.8,33.274234
3,Afghanistan,1993,2862.1,18.9,12313.3,81.1,15175.3,399.8,14,88.3,...,3181.0,21.0,11994.4,79.0,1148.3,7.6,5804.2,38.2,5041.8,33.223974
4,Afghanistan,1994,3148.5,19.1,13336.5,80.9,16485.0,439.9,14,97.1,...,3458.0,21.0,13027.1,79.0,1249.3,7.6,6309.1,38.3,5468.6,33.173067